# Tester les requetes et dataframe utilisés dans le Dashboard

In [2]:
import streamlit as st
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('../data/application_train_features.csv')
data = data.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
data.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307510 entries, 0 to 307509
Data columns (total 150 columns):
 #    Column                               Non-Null Count   Dtype
---   ------                               --------------   -----
 0    SK_ID_CURR                           307510 non-null  int64
 1    TARGET                               307510 non-null  float64
 2    FLAG_OWN_CAR                         307510 non-null  object
 3    FLAG_OWN_REALTY                      307510 non-null  int64
 4    CNT_CHILDREN                         307510 non-null  int64
 5    AMT_INCOME_TOTAL                     307510 non-null  float64
 6    AMT_CREDIT                           307510 non-null  float64
 7    AMT_ANNUITY                          307498 non-null  float64
 8    AMT_GOODS_PRICE                      307510 non-null  float64
 9    NAME_TYPE_SUITE                      306218 non-null  object
 10   NAME_INCOME_TYPE                     307510 non-null  object
 11   NAME_EDUCATION_TYPE                  307510 non-null  object
 12   NAME_FAMILY_STATUS                   307510 non-null  object
 13   NAME_HOUSING_TYPE                    307510 non-null  object
 14   REGION_POPULATION_RELATIVE           307510 non-null  float64
 15   DAYS_BIRTH                           307510 non-null  int64
 16   DAYS_EMPLOYED                        307510 non-null  float64
 17   DAYS_REGISTRATION                    307510 non-null  float64
 18   DAYS_ID_PUBLISH                      307510 non-null  int64
 19   OWN_CAR_AGE                          104582 non-null  float64
 20   FLAG_MOBIL                           307510 non-null  int64
 21   FLAG_EMP_PHONE                       307510 non-null  int64
 22   FLAG_WORK_PHONE                      307510 non-null  int64
 23   FLAG_CONT_MOBILE                     307510 non-null  int64
 24   FLAG_PHONE                           307510 non-null  int64
 25   FLAG_EMAIL                           307510 non-null  int64
 26   OCCUPATION_TYPE                      211119 non-null  object
 27   CNT_FAM_MEMBERS                      307510 non-null  float64
 28   REGION_RATING_CLIENT                 307510 non-null  int64
 29   REGION_RATING_CLIENT_W_CITY          307510 non-null  int64
 30   WEEKDAY_APPR_PROCESS_START           307510 non-null  object
 31   HOUR_APPR_PROCESS_START              307510 non-null  int64
 32   REG_REGION_NOT_LIVE_REGION           307510 non-null  int64
 33   REG_REGION_NOT_WORK_REGION           307510 non-null  int64
 34   LIVE_REGION_NOT_WORK_REGION          307510 non-null  int64
 35   REG_CITY_NOT_LIVE_CITY               307510 non-null  int64
 36   REG_CITY_NOT_WORK_CITY               307510 non-null  int64
 37   LIVE_CITY_NOT_WORK_CITY              307510 non-null  int64
 38   ORGANIZATION_TYPE                    307510 non-null  object
 39   EXT_SOURCE_1                         307510 non-null  float64
 40   EXT_SOURCE_2                         307510 non-null  float64
 41   EXT_SOURCE_3                         307510 non-null  float64
 42   APARTMENTS_AVG                       151449 non-null  float64
 43   BASEMENTAREA_AVG                     127567 non-null  float64
 44   YEARS_BEGINEXPLUATATION_AVG          157503 non-null  float64
 45   YEARS_BUILD_AVG                      103023 non-null  float64
 46   COMMONAREA_AVG                       92646 non-null   float64
 47   ELEVATORS_AVG                        143619 non-null  float64
 48   ENTRANCES_AVG                        152682 non-null  float64
 49   FLOORSMAX_AVG                        154490 non-null  float64
 50   FLOORSMIN_AVG                        98869 non-null   float64
 51   LANDAREA_AVG                         124920 non-null  float64
 52   LIVINGAPARTMENTS_AVG                 97312 non-null   float64
 53   LIVINGAREA_AVG                       153160 non-null  float64
 54   NONLIVINGAPARTMENTS_AVG              93997 non-null   float64
 55   NONLIVINGAREA_AVG                    137829 non-null  float64
 56   APARTMENTS_MODE                      151449 non-null  float64
 57   BASEMENTAREA_MODE                    127567 non-null  float64
 58   YEARS_BEGINEXPLUATATION_MODE         157503 non-null  float64
 59   YEARS_BUILD_MODE                     103023 non-null  float64
 60   COMMONAREA_MODE                      92646 non-null   float64
 61   ELEVATORS_MODE                       143619 non-null  float64
 62   ENTRANCES_MODE                       152682 non-null  float64
 63   FLOORSMAX_MODE                       154490 non-null  float64
 64   FLOORSMIN_MODE                       98869 non-null   float64
 65   LANDAREA_MODE                        124920 non-null  float64
 66   LIVINGAPARTMENTS_MODE                97312 non-null   float64
 67   LIVINGAREA_MODE                      153160 non-null  float64
 68   NONLIVINGAPARTMENTS_MODE             93997 non-null   float64
 69   NONLIVINGAREA_MODE                   137829 non-null  float64
 70   APARTMENTS_MEDI                      151449 non-null  float64
 71   BASEMENTAREA_MEDI                    127567 non-null  float64
 72   YEARS_BEGINEXPLUATATION_MEDI         157503 non-null  float64
 73   YEARS_BUILD_MEDI                     103023 non-null  float64
 74   COMMONAREA_MEDI                      92646 non-null   float64
 75   ELEVATORS_MEDI                       143619 non-null  float64
 76   ENTRANCES_MEDI                       152682 non-null  float64
 77   FLOORSMAX_MEDI                       154490 non-null  float64
 78   FLOORSMIN_MEDI                       98869 non-null   float64
 79   LANDAREA_MEDI                        124920 non-null  float64
 80   LIVINGAPARTMENTS_MEDI                97312 non-null   float64
 81   LIVINGAREA_MEDI                      153160 non-null  float64
 82   NONLIVINGAPARTMENTS_MEDI             93997 non-null   float64
 83   NONLIVINGAREA_MEDI                   137829 non-null  float64
 84   FONDKAPREMONT_MODE                   97216 non-null   object
 85   HOUSETYPE_MODE                       153213 non-null  object
 86   TOTALAREA_MODE                       159079 non-null  float64
 87   WALLSMATERIAL_MODE                   151169 non-null  object
 88   EMERGENCYSTATE_MODE                  161755 non-null  object
 89   OBS_30_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 90   DEF_30_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 91   OBS_60_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 92   DEF_60_CNT_SOCIAL_CIRCLE             306489 non-null  float64
 93   DAYS_LAST_PHONE_CHANGE               307509 non-null  float64
 94   FLAG_DOCUMENT_2                      307510 non-null  int64
 95   FLAG_DOCUMENT_3                      307510 non-null  int64
 96   FLAG_DOCUMENT_4                      307510 non-null  int64
 97   FLAG_DOCUMENT_5                      307510 non-null  int64
 98   FLAG_DOCUMENT_6                      307510 non-null  int64
 99   FLAG_DOCUMENT_7                      307510 non-null  int64
 100  FLAG_DOCUMENT_8                      307510 non-null  int64
 101  FLAG_DOCUMENT_9                      307510 non-null  int64
 102  FLAG_DOCUMENT_10                     307510 non-null  int64
 103  FLAG_DOCUMENT_11                     307510 non-null  int64
 104  FLAG_DOCUMENT_12                     307510 non-null  int64
 105  FLAG_DOCUMENT_13                     307510 non-null  int64
 106  FLAG_DOCUMENT_14                     307510 non-null  int64
 107  FLAG_DOCUMENT_15                     307510 non-null  int64
 108  FLAG_DOCUMENT_16                     307510 non-null  int64
 109  FLAG_DOCUMENT_17                     307510 non-null  int64
 110  FLAG_DOCUMENT_18                     307510 non-null  int64
 111  FLAG_DOCUMENT_19                     307510 non-null  int64
 112  FLAG_DOCUMENT_20                     307510 non-null  int64
 113  FLAG_DOCUMENT_21                     307510 non-null  int64
 114  AMT_REQ_CREDIT_BUREAU_HOUR           265991 non-null  float64
 115  AMT_REQ_CREDIT_BUREAU_DAY            265991 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_WEEK           265991 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_MON            265991 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_QRT            265991 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_YEAR           265991 non-null  float64
 120  NAME_CONTRACT_TYPE_CASH_LOAN         307510 non-null  int64
 121  NAME_CONTRACT_TYPE_REVOLVING_LOAN    307510 non-null  int64
 122  CNT_DOC_TOTAL                        307510 non-null  int64
 123  RATIO_INCOME_TO_FAM_MEMBERS          307510 non-null  float64
 124  RATIO_AMT_CREDIT_TO_AMT_GOODS_PRICE  307510 non-null  float64
 125  FLAG_STABLE_INCOME_TYPE              307510 non-null  int64
 126  FLAG_RISKED_ORGANIZATION_TYPE        307510 non-null  int64
 127  NEW_AMT_REQ_CREDIT_BUREAU_WEEK       265991 non-null  float64
 128  CNT_PREV                             307510 non-null  float64
 129  AMT_PREV_SUM                         307510 non-null  float64
 130  AMT_PREV_SUM_DEBT                    307510 non-null  float64
 131  AMT_PREV_SUM_OVERDUE                 307510 non-null  float64
 132  AMT_PREV_MAX_OVERDUE                 307510 non-null  float64
 133  CNT_CREDIT                           307510 non-null  float64
 134  AMT_CREDIT_SUM                       307510 non-null  float64
 135  AMT_CREDIT_SUM_DEBT                  307510 non-null  float64
 136  AMT_CREDIT_SUM_OVERDUE               307510 non-null  float64
 137  AMT_CREDIT_MAX_OVERDUE               307510 non-null  float64
 138  CNT_ALL                              307510 non-null  float64
 139  AMT_ALL_SUM                          307510 non-null  float64
 140  AMT_ALL_SUM_DEBT                     307510 non-null  float64
 141  AMT_ALL_SUM_OVERDUE                  307510 non-null  float64
 142  AMT_ALL_MAX_OVERDUE                  307510 non-null  float64
 143  CODE_GENDER_F                        307510 non-null  int64
 144  CODE_GENDER_M                        307510 non-null  int64
 145  CODE_GENDER_XNA                      307510 non-null  int64
 146  AMT_ALL_SUM_MEAN                     307510 non-null  float64
 147  RATIO_ALL_SUM_OVERDUE_TO_INCOME      307510 non-null  float64
 148  RATIO_ALL_MAX_OVERDUE_TO_INCOME      307510 non-null  float64
 149  RATIO_ALL_SUM_DEBT_TO_INCOME         307510 non-null  float64
dtypes: float64(89), int64(48), object(13)
memory usage: 351.9+ MB

In [10]:
client_base =  pd.read_csv('../data/application_test_features.csv')
client_base = client_base.iloc[:, 3:]  # Je supprime des colonnes de réplication des index (je ne sais pas d'où elles viennent mais pas grave)
client_base.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48744 entries, 0 to 48743
Data columns (total 150 columns):
 #    Column                               Non-Null Count  Dtype
---   ------                               --------------  -----
 0    SK_ID_CURR                           48744 non-null  int64
 1    TARGET                               0 non-null      float64
 2    FLAG_OWN_CAR                         48744 non-null  object
 3    FLAG_OWN_REALTY                      48744 non-null  int64
 4    CNT_CHILDREN                         48744 non-null  int64
 5    AMT_INCOME_TOTAL                     48744 non-null  float64
 6    AMT_CREDIT                           48744 non-null  float64
 7    AMT_ANNUITY                          48720 non-null  float64
 8    AMT_GOODS_PRICE                      48744 non-null  float64
 9    NAME_TYPE_SUITE                      47833 non-null  object
 10   NAME_INCOME_TYPE                     48744 non-null  object
 11   NAME_EDUCATION_TYPE                  48744 non-null  object
 12   NAME_FAMILY_STATUS                   48744 non-null  object
 13   NAME_HOUSING_TYPE                    48744 non-null  object
 14   REGION_POPULATION_RELATIVE           48744 non-null  float64
 15   DAYS_BIRTH                           48744 non-null  int64
 16   DAYS_EMPLOYED                        48744 non-null  float64
 17   DAYS_REGISTRATION                    48744 non-null  float64
 18   DAYS_ID_PUBLISH                      48744 non-null  int64
 19   OWN_CAR_AGE                          16432 non-null  float64
 20   FLAG_MOBIL                           48744 non-null  int64
 21   FLAG_EMP_PHONE                       48744 non-null  int64
 22   FLAG_WORK_PHONE                      48744 non-null  int64
 23   FLAG_CONT_MOBILE                     48744 non-null  int64
 24   FLAG_PHONE                           48744 non-null  int64
 25   FLAG_EMAIL                           48744 non-null  int64
 26   OCCUPATION_TYPE                      33139 non-null  object
 27   CNT_FAM_MEMBERS                      48744 non-null  float64
 28   REGION_RATING_CLIENT                 48744 non-null  int64
 29   REGION_RATING_CLIENT_W_CITY          48744 non-null  int64
 30   WEEKDAY_APPR_PROCESS_START           48744 non-null  object
 31   HOUR_APPR_PROCESS_START              48744 non-null  int64
 32   REG_REGION_NOT_LIVE_REGION           48744 non-null  int64
 33   REG_REGION_NOT_WORK_REGION           48744 non-null  int64
 34   LIVE_REGION_NOT_WORK_REGION          48744 non-null  int64
 35   REG_CITY_NOT_LIVE_CITY               48744 non-null  int64
 36   REG_CITY_NOT_WORK_CITY               48744 non-null  int64
 37   LIVE_CITY_NOT_WORK_CITY              48744 non-null  int64
 38   ORGANIZATION_TYPE                    48744 non-null  object
 39   EXT_SOURCE_1                         48744 non-null  float64
 40   EXT_SOURCE_2                         48744 non-null  float64
 41   EXT_SOURCE_3                         48744 non-null  float64
 42   APARTMENTS_AVG                       24857 non-null  float64
 43   BASEMENTAREA_AVG                     21103 non-null  float64
 44   YEARS_BEGINEXPLUATATION_AVG          25888 non-null  float64
 45   YEARS_BUILD_AVG                      16926 non-null  float64
 46   COMMONAREA_AVG                       15249 non-null  float64
 47   ELEVATORS_AVG                        23555 non-null  float64
 48   ENTRANCES_AVG                        25165 non-null  float64
 49   FLOORSMAX_AVG                        25423 non-null  float64
 50   FLOORSMIN_AVG                        16278 non-null  float64
 51   LANDAREA_AVG                         20490 non-null  float64
 52   LIVINGAPARTMENTS_AVG                 15964 non-null  float64
 53   LIVINGAREA_AVG                       25192 non-null  float64
 54   NONLIVINGAPARTMENTS_AVG              15397 non-null  float64
 55   NONLIVINGAREA_AVG                    22660 non-null  float64
 56   APARTMENTS_MODE                      24857 non-null  float64
 57   BASEMENTAREA_MODE                    21103 non-null  float64
 58   YEARS_BEGINEXPLUATATION_MODE         25888 non-null  float64
 59   YEARS_BUILD_MODE                     16926 non-null  float64
 60   COMMONAREA_MODE                      15249 non-null  float64
 61   ELEVATORS_MODE                       23555 non-null  float64
 62   ENTRANCES_MODE                       25165 non-null  float64
 63   FLOORSMAX_MODE                       25423 non-null  float64
 64   FLOORSMIN_MODE                       16278 non-null  float64
 65   LANDAREA_MODE                        20490 non-null  float64
 66   LIVINGAPARTMENTS_MODE                15964 non-null  float64
 67   LIVINGAREA_MODE                      25192 non-null  float64
 68   NONLIVINGAPARTMENTS_MODE             15397 non-null  float64
 69   NONLIVINGAREA_MODE                   22660 non-null  float64
 70   APARTMENTS_MEDI                      24857 non-null  float64
 71   BASEMENTAREA_MEDI                    21103 non-null  float64
 72   YEARS_BEGINEXPLUATATION_MEDI         25888 non-null  float64
 73   YEARS_BUILD_MEDI                     16926 non-null  float64
 74   COMMONAREA_MEDI                      15249 non-null  float64
 75   ELEVATORS_MEDI                       23555 non-null  float64
 76   ENTRANCES_MEDI                       25165 non-null  float64
 77   FLOORSMAX_MEDI                       25423 non-null  float64
 78   FLOORSMIN_MEDI                       16278 non-null  float64
 79   LANDAREA_MEDI                        20490 non-null  float64
 80   LIVINGAPARTMENTS_MEDI                15964 non-null  float64
 81   LIVINGAREA_MEDI                      25192 non-null  float64
 82   NONLIVINGAPARTMENTS_MEDI             15397 non-null  float64
 83   NONLIVINGAREA_MEDI                   22660 non-null  float64
 84   FONDKAPREMONT_MODE                   15947 non-null  object
 85   HOUSETYPE_MODE                       25125 non-null  object
 86   TOTALAREA_MODE                       26120 non-null  float64
 87   WALLSMATERIAL_MODE                   24851 non-null  object
 88   EMERGENCYSTATE_MODE                  26535 non-null  object
 89   OBS_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 90   DEF_30_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 91   OBS_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 92   DEF_60_CNT_SOCIAL_CIRCLE             48715 non-null  float64
 93   DAYS_LAST_PHONE_CHANGE               48744 non-null  float64
 94   FLAG_DOCUMENT_2                      48744 non-null  int64
 95   FLAG_DOCUMENT_3                      48744 non-null  int64
 96   FLAG_DOCUMENT_4                      48744 non-null  int64
 97   FLAG_DOCUMENT_5                      48744 non-null  int64
 98   FLAG_DOCUMENT_6                      48744 non-null  int64
 99   FLAG_DOCUMENT_7                      48744 non-null  int64
 100  FLAG_DOCUMENT_8                      48744 non-null  int64
 101  FLAG_DOCUMENT_9                      48744 non-null  int64
 102  FLAG_DOCUMENT_10                     48744 non-null  int64
 103  FLAG_DOCUMENT_11                     48744 non-null  int64
 104  FLAG_DOCUMENT_12                     48744 non-null  int64
 105  FLAG_DOCUMENT_13                     48744 non-null  int64
 106  FLAG_DOCUMENT_14                     48744 non-null  int64
 107  FLAG_DOCUMENT_15                     48744 non-null  int64
 108  FLAG_DOCUMENT_16                     48744 non-null  int64
 109  FLAG_DOCUMENT_17                     48744 non-null  int64
 110  FLAG_DOCUMENT_18                     48744 non-null  int64
 111  FLAG_DOCUMENT_19                     48744 non-null  int64
 112  FLAG_DOCUMENT_20                     48744 non-null  int64
 113  FLAG_DOCUMENT_21                     48744 non-null  int64
 114  AMT_REQ_CREDIT_BUREAU_HOUR           42695 non-null  float64
 115  AMT_REQ_CREDIT_BUREAU_DAY            42695 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_WEEK           42695 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_MON            42695 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_QRT            42695 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_YEAR           42695 non-null  float64
 120  NAME_CONTRACT_TYPE_CASH_LOAN         48744 non-null  int64
 121  NAME_CONTRACT_TYPE_REVOLVING_LOAN    48744 non-null  int64
 122  CNT_DOC_TOTAL                        48744 non-null  int64
 123  RATIO_INCOME_TO_FAM_MEMBERS          48744 non-null  float64
 124  RATIO_AMT_CREDIT_TO_AMT_GOODS_PRICE  48744 non-null  float64
 125  FLAG_STABLE_INCOME_TYPE              48744 non-null  int64
 126  FLAG_RISKED_ORGANIZATION_TYPE        48744 non-null  int64
 127  NEW_AMT_REQ_CREDIT_BUREAU_WEEK       42695 non-null  float64
 128  CNT_PREV                             48744 non-null  float64
 129  AMT_PREV_SUM                         48744 non-null  float64
 130  AMT_PREV_SUM_DEBT                    48744 non-null  float64
 131  AMT_PREV_SUM_OVERDUE                 48744 non-null  float64
 132  AMT_PREV_MAX_OVERDUE                 48744 non-null  float64
 133  CNT_CREDIT                           48744 non-null  float64
 134  AMT_CREDIT_SUM                       48744 non-null  float64
 135  AMT_CREDIT_SUM_DEBT                  48744 non-null  float64
 136  AMT_CREDIT_SUM_OVERDUE               48744 non-null  float64
 137  AMT_CREDIT_MAX_OVERDUE               48744 non-null  float64
 138  CNT_ALL                              48744 non-null  float64
 139  AMT_ALL_SUM                          48744 non-null  float64
 140  AMT_ALL_SUM_DEBT                     48744 non-null  float64
 141  AMT_ALL_SUM_OVERDUE                  48744 non-null  float64
 142  AMT_ALL_MAX_OVERDUE                  48744 non-null  float64
 143  CODE_GENDER_F                        48744 non-null  int64
 144  CODE_GENDER_M                        48744 non-null  int64
 145  CODE_GENDER_XNA                      48744 non-null  int64
 146  AMT_ALL_SUM_MEAN                     48744 non-null  float64
 147  RATIO_ALL_SUM_OVERDUE_TO_INCOME      48744 non-null  float64
 148  RATIO_ALL_MAX_OVERDUE_TO_INCOME      48744 non-null  float64
 149  RATIO_ALL_SUM_DEBT_TO_INCOME         48744 non-null  float64
dtypes: float64(89), int64(48), object(13)
memory usage: 55.8+ MB

In [12]:
client_base.head()

,SK_ID_CURR,TARGET,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,...,AMT_ALL_SUM_DEBT,AMT_ALL_SUM_OVERDUE,AMT_ALL_MAX_OVERDUE,CODE_GENDER_F,CODE_GENDER_M,CODE_GENDER_XNA,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME,RATIO_ALL_SUM_DEBT_TO_INCOME
0,100001,NaN,N,1,0,135000.0,568800.0,20560.5,450000.0,Unaccompanied,...,595173.600,0.000,0.000,1,0,0,184644.000000,0.000000,0.000000,4.408693
1,100005,NaN,N,1,0,99000.0,222768.0,17370.0,180000.0,Unaccompanied,...,557213.355,0.000,4813.200,0,1,0,174319.875000,0.000000,0.583418,5.628418
2,100013,NaN,Y,1,0,202500.0,663264.0,69777.0,630000.0,NaN,...,-373892.625,171562.725,23153.985,0,1,0,379545.222857,0.847223,1.372088,-1.846383
3,100028,NaN,N,1,2,315000.0,1575000.0,49018.5,1575000.0,Unaccompanied,...,218010.465,70348.230,11250.000,1,0,0,129077.472000,0.223328,0.428571,0.692097
4,100038,NaN,Y,0,1,180000.0,625500.0,32067.0,625500.0,Unaccompanied,...,-29497.950,0.000,0.000,0,1,0,92605.500000,0.000000,0.000000,-0.163878

In [11]:
domain_features=['DAYS_BIRTH', 'CODE_GENDER_F', 'FLAG_RISKED_ORGANIZATION_TYPE', 
                 'RATIO_INCOME_TO_FAM_MEMBERS', 'FLAG_STABLE_INCOME_TYPE',
                 'EXT_SOURCE_2',
                 'AMT_ALL_SUM_MEAN', 'RATIO_ALL_SUM_DEBT_TO_INCOME', 'RATIO_ALL_SUM_OVERDUE_TO_INCOME', 'RATIO_ALL_MAX_OVERDUE_TO_INCOME']

In [17]:
id_client = 100028
client_base.loc[client_base['SK_ID_CURR'] == id_client, domain_features]

,DAYS_BIRTH,CODE_GENDER_F,FLAG_RISKED_ORGANIZATION_TYPE,RATIO_INCOME_TO_FAM_MEMBERS,FLAG_STABLE_INCOME_TYPE,EXT_SOURCE_2,AMT_ALL_SUM_MEAN,RATIO_ALL_SUM_DEBT_TO_INCOME,RATIO_ALL_SUM_OVERDUE_TO_INCOME,RATIO_ALL_MAX_OVERDUE_TO_INCOME
3,-13976,1,0,78750.0,0,0.509677,129077.472,0.692097,0.223328,0.428571